#!/usr/bin/perl
#----------------------------------------------------------------------
#
# generate-injection-points.pl
#	Scan the backend sources for injection point call sites and emit
#	them as a C table, so that the module can report at run time which
#	points this build defines.
#
# There is no other registry of defined points: the macros take string
# literals and InjectionPointAttach() accepts any name without
# complaint, so a caller attaching to a point that no longer exists
# gets silence rather than an error.  The table this generates is what
# lets injection_points_defined() answer, and with it a test suite can
# tell a stale name from a live one and derive coverage instead of
# maintaining a hand-written list.
#
# Every call site with a literal name is one row: name, file relative
# to src/backend, line, and which macro it was --
#
#   INJECTION_POINT              run
#   INJECTION_POINT_CACHED       cached
#   INJECTION_POINT_LOAD         load
#   IS_INJECTION_POINT_ATTACHED  attached
#
# The macro matters to a consumer: LOAD/CACHED mark a point reached
# from inside a critical section, and an ATTACHED site changes the
# server's behaviour on mere attachment, so a callback that only means
# to add delay must stay away from that name.
#
# Non-literal names do not match, which is the right thing: the only
# ones in the tree are this module's own SQL wrappers, and a name that
# is not a literal is not a point a scan can promise anything about.
#
# The output is rewritten only when its content changes, so a build
# that runs this every time does not relink anything for it.
#
# Copyright (c) 2026, PostgreSQL Global Development Group
#
# src/test/modules/injection_points/generate-injection-points.pl
#
#----------------------------------------------------------------------

use strict;
use warnings FATAL => 'all';

use File::Find;
use Getopt::Long;

my $srcdir;
my $outfile;
my $stub = 0;

GetOptions(
	'srcdir=s' => \$srcdir,
	'outfile=s' => \$outfile,
	'stub' => \$stub) or die "$0: wrong arguments";

die "$0: --outfile is required\n" unless defined $outfile;
die "$0: --srcdir is required unless --stub\n"
  unless $stub || defined $srcdir;

my %kind_of = (
	INJECTION_POINT => 'run',
	INJECTION_POINT_CACHED => 'cached',
	INJECTION_POINT_LOAD => 'load',
	IS_INJECTION_POINT_ATTACHED => 'attached');

my @rows;

sub scan_file
{
	my ($path, $relpath) = @_;

	local $/;
	open my $fh, '<', $path or die "$0: cannot read $path: $!\n";
	my $src = <$fh>;
	close $fh;

	# Blank out comments so a mention of a macro in prose does not
	# become a row, keeping every newline so line numbers stay right.
	$src =~ s{(/\*.*?\*/)}{ my $c = $1; $c =~ tr/\n//cd; $c }gse;
	$src =~ s{//[^\n]*}{}g;

	# Longest alternatives first, or INJECTION_POINT would eat the
	# prefix of its CACHED and LOAD forms.
	while ($src =~ m{\b(IS_INJECTION_POINT_ATTACHED
			|INJECTION_POINT_CACHED
			|INJECTION_POINT_LOAD
			|INJECTION_POINT)
			\s*\(\s*"([^"]+)"}gx)
	{
		my ($macro, $name) = ($1, $2);
		my $line = 1 + substr($src, 0, $-[0]) =~ tr/\n//;

		push @rows,
		  {
			name => $name,
			file => $relpath,
			line => $line,
			kind => $kind_of{$macro},
		  };
	}
	return;
}

unless ($stub)
{
	my $root = "$srcdir/src/backend";
	die "$0: $root does not exist\n" unless -d $root;

	my @files;
	find(
		sub {
			push @files, $File::Find::name if /\.c$/ && -f;
		},
		$root);

	foreach my $path (sort @files)
	{
		(my $rel = $path) =~ s{^\Q$root\E/}{};
		scan_file($path, $rel);
	}
}

@rows = sort {
	$a->{name} cmp $b->{name}
	  || $a->{file} cmp $b->{file}
	  || $a->{line} <=> $b->{line}
} @rows;

my $out = <<'EOM';
/*
 * injection_point_defs.h
 *		Injection point call sites found in the backend sources.
 *
 * Generated by generate-injection-points.pl, do not edit.  A row per
 * call site with a literal name; the table ends at the NULL sentinel.
 */
static const InjectionPointDef injection_point_defs[] = {
EOM

foreach my $r (@rows)
{
	$out .= sprintf "\t{\"%s\", \"%s\", %d, \"%s\"},\n",
	  $r->{name}, $r->{file}, $r->{line}, $r->{kind};
}
$out .= "\t{NULL, NULL, 0, NULL}\n};\n";

# Rewrite only on change, so the file's mtime does not force a rebuild
# of everything that includes it.
my $existing = '';
if (open my $fh, '<', $outfile)
{
	local $/;
	$existing = <$fh>;
	close $fh;
}

if ($existing ne $out)
{
	open my $fh, '>', "$outfile.tmp"
	  or die "$0: cannot write $outfile.tmp: $!\n";
	print $fh $out;
	close $fh;
	rename "$outfile.tmp", $outfile
	  or die "$0: cannot rename $outfile.tmp: $!\n";
}
