#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/jam
#
# IDENTIFICATION
#    src/backend/access/jam/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/jam
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	jam.o

include $(top_srcdir)/src/backend/common.mk
