# Copyright (c) 2026, PostgreSQL Global Development Group

tests += {
  'name': 'stress',
  'sd': meson.current_source_dir(),
  'bd': meson.current_build_dir(),
  'tap': {
    'tests': [
      't/001_repack_updates.pl',
      't/002_repack_inserts.pl',
      't/003_cic.pl',
      't/004_cic_ams.pl',
      't/005_refresh_matview.pl',
      't/006_detach_partition.pl',
      't/007_logical_replication.pl',
      't/008_replication_slots.pl',
      't/009_serializable.pl',
      't/010_replication_ddl.pl',
      't/011_standby.pl',
      't/012_crash_recovery.pl',
      't/013_twophase.pl',
      't/014_vacuum.pl',
      't/015_toast.pl',
      't/016_foreign_keys.pl',
      't/017_bulk_load.pl',
      't/018_upsert_merge.pl',
      't/019_plancache.pl',
      't/020_cursors.pl',
      't/021_partitioned.pl',
      't/022_subscriber_contention.pl',
      't/023_tablesync.pl',
      't/024_pg_dump.pl',
      't/025_cancellation.pl',
      't/026_multi_table.pl',
      't/027_cross_database.pl',
      't/028_generated.pl',
      't/029_function_index.pl',
      't/030_alter_table.pl',
      't/031_replica_role.pl',
      't/032_lock_exhaustion.pl',
      't/033_row_locking.pl',
      't/034_subtransactions.pl',
      't/035_index_only.pl',
      't/036_exclusion.pl',
    ],
  },
}
