# Copyright (c) 2026, PostgreSQL Global Development Group

tests += {
  'name': 'stress',
  'sd': meson.current_source_dir(),
  'bd': meson.current_build_dir(),
  'tap': {
    'env': {
       'enable_injection_points': get_option('injection_points') ? 'yes' : 'no',
    },
    'tests': [
      't/001_meta.pl',
      't/100_repack_dml_s1.pl',
      't/101_repack_dml_s50.pl',
      't/102_locks_and_subxacts.pl',
      't/103_unique_and_gapless.pl',
      't/104_rewrite_fidelity.pl',
      't/105_foreign_keys.pl',
      't/106_partitions.pl',
      't/107_vacuum_and_ios.pl',
      't/108_bulk_and_rewrite.pl',
      't/109_plancache_and_matview.pl',
      't/110_overlapping_ddl.pl',
      't/111_lock_exhaustion.pl',
      't/112_standby.pl',
      't/113_subscription.pl',
      't/114_crash_recovery.pl',
      't/115_cancellation.pl',
      't/116_access_methods.pl',
      't/117_partitioned_pgbench.pl',
      't/118_hot_prune.pl',
      't/119_hash_and_constraints.pl',
      't/120_index_build_churn.pl',
      't/121_triggers.pl',
      't/122_decoding_startup_race.pl',
      't/123_ios_vacuum_race.pl',
      't/124_bitmap_skip_fetch.pl',
      't/125_data_checksums.pl',
      't/126_data_checksums_standby.pl',
      't/127_data_checksums_crash.pl',
      't/128_moving_identity.pl',
      't/129_moving_identity_sub.pl',
      't/999_soak.pl',
    ],
  },
}
