# REPACK (CONCURRENTLY) ... USING INDEX ...;
setup
{
	CREATE EXTENSION injection_points;

	CREATE TABLE repack_test(i int PRIMARY KEY, j int);
	INSERT INTO repack_test(i, j) VALUES (1, 1), (2, 2), (3, 3), (4, 4);
	CREATE TABLE repack_test_y(i int);

	CREATE TABLE relfilenodes(node oid);

	CREATE TABLE data_s1(i int, j int);
	CREATE TABLE data_s2(i int, j int);
}

teardown
{
	DROP TABLE repack_test;
	DROP TABLE repack_test_y;
	DROP EXTENSION injection_points;

	DROP TABLE relfilenodes;
	DROP TABLE data_s1;
	DROP TABLE data_s2;
}

session s1
setup
{
	SELECT injection_points_set_local();
	SELECT injection_points_attach('repack-concurrently-before-lock', 'wait');
}
# Perform the initial load and wait for s2 to do some data changes.
step wait_before_lock
{
	REPACK (CONCURRENTLY) repack_test USING INDEX repack_test_pkey;
}
# Check the table from the perspective of s1.
#
# Besides the contents, we also check that relfilenode has changed.

# Have each session write the contents into a table and use FULL JOIN to check
# if the outputs are identical.
step check1
{
	INSERT INTO relfilenodes(node)
	SELECT relfilenode FROM pg_class WHERE relname='repack_test';

	SELECT count(DISTINCT node) FROM relfilenodes;

	SELECT i, j FROM repack_test ORDER BY i, j;

	INSERT INTO data_s1(i, j)
	SELECT i, j FROM repack_test;

	SELECT count(*)
	FROM data_s1 d1 FULL JOIN data_s2 d2 USING (i, j)
	WHERE d1.i ISNULL OR d2.i ISNULL;
}
teardown
{
	SELECT injection_points_detach('repack-concurrently-before-lock');
}

session s2
step s2_timeout_fast
{
	SET deadlock_timeout = '10ms';
}
# Change the existing data. UPDATE changes both key and non-key columns. Also
# update one row twice to test whether tuple version generated by this session
# can be found.
step change_existing
{
	UPDATE repack_test SET i=10 where i=1;
	UPDATE repack_test SET j=20 where i=2;
	UPDATE repack_test SET i=30 where i=3;
	UPDATE repack_test SET i=40 where i=30;
	DELETE FROM repack_test WHERE i=4;
}
# Insert new rows and UPDATE / DELETE some of them. Again, update both key and
# non-key column.
step change_new
{
	INSERT INTO repack_test(i, j) VALUES (5, 5), (6, 6), (7, 7), (8, 8);
	UPDATE repack_test SET i=50 where i=5;
	UPDATE repack_test SET j=60 where i=6;
	DELETE FROM repack_test WHERE i=7;
}

# When applying concurrent data changes, we should see the effects of an
# in-progress subtransaction.
#
# XXX Not sure this test is useful now - it was designed for the patch that
# preserves tuple visibility and which therefore modifies
# TransactionIdIsCurrentTransactionId().
step change_subxact1
{
	BEGIN;
	INSERT INTO repack_test(i, j) VALUES (100, 100);
	SAVEPOINT s1;
	UPDATE repack_test SET i=101 where i=100;
	SAVEPOINT s2;
	UPDATE repack_test SET i=102 where i=101;
	COMMIT;
}

# When applying concurrent data changes, we should not see the effects of a
# rolled back subtransaction.
#
# XXX Is this test useful? See above.
step change_subxact2
{
	BEGIN;
	SAVEPOINT s1;
	INSERT INTO repack_test(i, j) VALUES (110, 110);
	ROLLBACK TO SAVEPOINT s1;
	INSERT INTO repack_test(i, j) VALUES (110, 111);
	COMMIT;
}

# Check the table from the perspective of s2.
step check2
{
	INSERT INTO relfilenodes(node)
	SELECT relfilenode FROM pg_class WHERE relname='repack_test';

	SELECT i, j FROM repack_test ORDER BY i, j;

	INSERT INTO data_s2(i, j)
	SELECT i, j FROM repack_test;
}
step wakeup_before_lock
{
	SELECT injection_points_wakeup('repack-concurrently-before-lock');
}
# Steps used in lock contention tests.
step begin_txn
{
	BEGIN;
}
step begin_and_read
{
	BEGIN;
	SELECT 1 FROM repack_test LIMIT 1;
}
step lock_table_ae
{
	LOCK TABLE repack_test IN ACCESS EXCLUSIVE MODE;
}
step lock_table_sue
{
	LOCK TABLE repack_test IN SHARE UPDATE EXCLUSIVE MODE;
}
step lock_table_y_sue
{
	LOCK TABLE repack_test_y IN SHARE UPDATE EXCLUSIVE MODE;
}
step end_txn
{
	COMMIT;
}

session s3
step s3_begin_txn
{
	BEGIN;
}
step s3_lock_table_y_sue
{
	LOCK TABLE repack_test_y IN SHARE UPDATE EXCLUSIVE MODE;
}
step s3_lock_table_sue
{
	LOCK TABLE repack_test IN SHARE UPDATE EXCLUSIVE MODE;
}
step s3_wakeup
{
	SELECT injection_points_wakeup('repack-concurrently-before-lock');
}
step s3_end_txn
{
	COMMIT;
}

session s4
step s4_wakeup
{
	SELECT injection_points_wakeup('repack-concurrently-before-lock');
}

# Test if data changes introduced while one session is performing REPACK
# CONCURRENTLY find their way into the table.
permutation
	wait_before_lock
	change_existing
	change_new
	change_subxact1
	change_subxact2
	check2
	wakeup_before_lock
	check1

# A waiter that does not already hold a conflicting lock on the table is not a
# future deadlock.  It waits until REPACK finishes and then acquires its lock.
permutation
	wait_before_lock
	begin_txn
	lock_table_ae
	s3_wakeup
	end_txn

# In the deadlock-expecting permutations below, all deadlock detections must
# run while s1 is still parked at the injection point, i.e. before s1 wakes
# up and attempts AccessExclusiveLock.  Once s1 attaches waitLink for AEL,
# it clears its future-wait slot, and any cycle from that point on would be
# reported as a plain "deadlock detected" rather than "future deadlock
# detected".  To force this ordering, every wakeup step is placed after the
# COMMIT from the session whose 10 ms deadlock_timeout we rely on: the
# framework cannot run that COMMIT until the blocked session has unblocked
# (via its deadlock check), so the wakeup necessarily follows.

# A waiter that already holds AccessShareLock then waits for AccessExclusiveLock
# behind REPACK's ShareUpdateExclusiveLock.
permutation
	s2_timeout_fast
	wait_before_lock
	begin_and_read
	lock_table_ae(*)
	end_txn
	s3_wakeup

# Same shape as above, but the waiter requests ShareUpdateExclusiveLock.
permutation
	s2_timeout_fast
	wait_before_lock
	begin_and_read
	lock_table_sue(*)
	end_txn
	s3_wakeup

# Three-backend future deadlock:
#
# - s1 holds ShareUpdateExclusiveLock on repack_test and has declared a future
#   AccessExclusiveLock on it.
# - s2 holds AccessShareLock on repack_test.
# - s3 holds ShareUpdateExclusiveLock on repack_test_y, then waits for
#   ShareUpdateExclusiveLock on repack_test behind s1.
# - s2 waits for ShareUpdateExclusiveLock on repack_test_y behind s3.
permutation
	s2_timeout_fast
	wait_before_lock
	begin_and_read
	s3_begin_txn
	s3_lock_table_y_sue
	s3_lock_table_sue
	lock_table_y_sue(*)
	end_txn
	s4_wakeup
	s3_end_txn
